"""
situations.py — the site's "Design for a situation" pages, from situation-index.json.

A designer arrives with learners, a goal and a setting, not with the name of a principle.
The guidance for that lives in the `## Fitting the design to a situation` tables of the
converted principle and pattern pages, and until now a reader could reach a row only from
its own page. These pages turn that around: one page per tag (`novice`,
`online-self-paced`, `procedure`, ...) listing every row that speaks to it, grouped by the
page it comes from, with the row's basis. Pages whose rows cite claims come first.

The rows are generated by scripts/build_situation_index.py and nothing here edits a wiki
page. Links in a row are bundle-relative in the index (`claims/x.md`) and are written here
relative to `situations/`; the two_tier hook, which runs after this one is registered,
then points links to long-tail pages at their directory URLs as it does everywhere.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "situation-index.json"
GROUP_TITLES = {"learners": "Learners", "goal": "Learning goal", "context": "Context"}
FIELD_TITLES = {"expertise": "Expertise", "age": "Age", "population_band": "Population",
                "knowledge_type": "Kind of goal", "element_interactivity": "Element interactivity",
                "setting": "Setting", "duration": "Duration"}
_FOLDER = {"principles": "Principle", "patterns": "Pattern", "elements": "Element", "designs": "Design"}


def _load():
    if not INDEX.exists():
        return None
    return json.loads(INDEX.read_text(encoding="utf-8"))


def _rel(text: str) -> str:
    """Bundle-relative links in a cell, made relative to situations/<tag>.md."""
    import re
    return re.sub(r"\]\((<?)(?=[a-z-]+/)", r"](\1../", text)


def _cell(text: str) -> str:
    return _rel(text).replace("\n", " ")


def index_markdown(idx: dict) -> str:
    lines = ["# Design for a situation", "",
             "What the wiki's principle and pattern pages say to change for particular learners, "
             "goals and settings. Each converted page ends its default design with a table, "
             "*If the brief says… / Then change… / Basis*; these pages collect those rows by the "
             "situation they name, so a learner and context analysis can start here rather than "
             "from the name of a principle.", "",
             f"{len(idx['rows']):,} rows from {len(idx['pages'])} pages. A row's basis is a claim, "
             "with its evidence marker, or the word *untested*. The tags are the controlled values "
             "of the wiki's evidence dimensions; a row that names its situation in words rather "
             "than a tag is listed under the tag its wording names (\"one session only\" under "
             "single-session), marked *(from the wording)*.", "",
             "Agents can ask the same question of the MCP server's `situations` tool, combining tags "
             "and words (for example novice learners, a self-paced course and a procedure).", ""]
    for group in ("learners", "goal", "context"):
        tags = [(t, v) for t, v in idx["tags"].items() if v["group"] == group]
        if not tags:
            continue
        lines += [f"## {GROUP_TITLES[group]}", "", "| Situation | What it means | Rows | Rows citing a claim |",
                  "|---|---|---|---|"]
        for tag, v in sorted(tags, key=lambda kv: (kv[1]["field"], -kv[1]["rows"])):
            lines.append(f"| [`{tag}`]({tag}.md) ({FIELD_TITLES.get(v['field'], v['field']).lower()}) "
                         f"| {v['meaning']} | {v['rows']} | {v['with_claim']} |")
        lines.append("")
    lines += ["## Pages with a situation table", ""]
    for key, p in sorted(idx["pages"].items(), key=lambda kv: kv[1]["title"].lower()):
        folder = key.split("/")[0]
        lines.append(f"* [{p['title']}](../{key}.md) <small>{_FOLDER.get(folder, folder)} · {p['rows']} rows</small>")
    return "\n".join(lines) + "\n"


def tag_markdown(tag: str, idx: dict) -> str:
    v = idx["tags"][tag]
    rows = [r for r in idx["rows"] if tag in r["tags"] or tag in r["inferred_tags"]]
    by_page = {}
    for r in rows:
        by_page.setdefault(r["page"], []).append(r)
    order = sorted(by_page, key=lambda k: (-sum(r["basis_kind"] == "claim" for r in by_page[k]),
                                           idx["pages"][k]["title"].lower()))
    field = FIELD_TITLES.get(v["field"], v["field"])
    lines = [f"# Designing for `{tag}`", "",
             f"> **{field}** · {v['meaning']} · [All situations](index.md)", "",
             f"{len(rows)} rows from {len(by_page)} pages say what to change when the brief's "
             f"{field.lower()} is `{tag}`; {v['with_claim']} of them cite a claim. Pages whose rows "
             "cite claims come first. Read the basis before relying on a row: many carry a claim "
             "to learners or settings it did not test, and say so.", ""]
    for key in order:
        p = idx["pages"][key]
        folder = key.split("/")[0]
        lines += [f"## [{p['title']}](../{key}.md)", "", f"<small>{_FOLDER.get(folder, folder)}</small>", "",
                  "| If the brief says… | Then change… | Basis |", "|---|---|---|"]
        for r in by_page[key]:
            mark = " *(from the wording)*" if tag in r["inferred_tags"] else ""
            lines.append(f"| {_cell(r['if'])}{mark} | {_cell(r['change'])} | {_cell(r['basis'])} |")
        lines.append("")
    return "\n".join(lines) + "\n"


def on_files(files, config):
    idx = _load()
    if not idx:
        return files
    from mkdocs.structure.files import File
    files.append(File.generated(config, "situations/index.md", content=index_markdown(idx)))
    for tag in idx["tags"]:
        files.append(File.generated(config, f"situations/{tag}.md", content=tag_markdown(tag, idx)))
    return files
