#!/usr/bin/env python3
"""
build_evidence_report.py — `evidence.md`, the state of the wiki's evidence.

Everything on the page is computed by evidence_rollup.py from the claim pages'
frontmatter codes and the `[±~][SMW]` markers on the pages that cite them. It
is regenerated, never edited: build_indexes.py rewrites it with the other
generated files, and `--check` fails when the committed copy is stale.

What it deliberately leaves out, because the data cannot carry it:

- **No ranking of strategies by effect.** `i` is a coarse bin, 60% of entries
  report no effect size, and the studies behind two strategies measure
  different outcomes in different populations. A league table would be the
  most quoted thing on the page and the least true.
- **No vote count.** Cited-for versus cited-against says how pages use a
  claim, not what the studies found.
- **No pooled effect size, until one is possible.** Pooling needs effect sizes
  with their uncertainty on a shared scale, for comparable contrasts and
  outcomes. That lives in observations/, and the page says how far it is from
  the first poolable family rather than estimating anything.

    python3 scripts/build_evidence_report.py            # write evidence.md
    python3 scripts/build_evidence_report.py --check    # exit 1 if stale
"""
import argparse
import statistics
import sys
from collections import Counter, defaultdict
from pathlib import Path

import yaml

WIKI_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(Path(__file__).parent))
import build_reverse_index  # noqa: E402
import evidence_rollup as er  # noqa: E402

OUT = WIKI_ROOT / "evidence.md"
SMD_TYPES = {"cohens_d", "hedges_g", "standardized_mean_difference"}
CONVERTIBLE = {"correlation", "odds_ratio", "risk_ratio", "partial_eta_squared", "eta_squared"}


def _cell(text) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def _short(citation: str, n: int = 110) -> str:
    c = " ".join(str(citation).split())
    return c if len(c) <= n else c[:n].rsplit(" ", 1)[0] + " …"


def _pct(a, b) -> str:
    return f"{round(100 * a / b)}%" if b else "–"


def build() -> str:
    reverse = build_reverse_index.build()
    claims = er.load_claims()
    cites = er.citations_by_page(reverse)
    all_slugs = list(claims)
    studies = er.Studies(claims, all_slugs)
    entries = sum(len(c["sources"]) for c in claims.values())

    # claims per study, and claims resting on a study alone
    claims_of = defaultdict(set)
    for slug, c in claims.items():
        for s in c["sources"]:
            claims_of[er.study_key(s)].add(slug)
    per_claim = {slug: len({er.study_key(s) for s in c["sources"]}) for slug, c in claims.items()}
    alone = Counter()
    for slug, n in per_claim.items():
        if n == 1:
            alone[er.study_key(claims[slug]["sources"][0])] += 1

    # citing pages per claim, and their markers
    citing = defaultdict(list)
    for claim, by_kind in reverse["edges"].get("claims", {}).items():
        for kind, es in by_kind.items():
            if kind == "claims":
                continue
            citing[claim].extend(e.get("polarity") for e in es)

    qs = Counter(studies.q(k) for k in studies.entries)
    with_effect = sum(1 for k in studies.entries if studies.reports_effect(k))
    n_claims = len(claims)
    spc = Counter(min(n, 4) for n in per_claim.values())

    L = []
    w = L.append
    w("# State of the Evidence")
    w("")
    w("> Generated by `scripts/build_evidence_report.py` from the claim pages' evidence codes and the "
      "`[±~][SMW]` markers on the pages that cite them. Do not edit by hand.")
    w("")
    w("What the wiki's evidence adds up to. Every number counts **distinct studies**, keyed by DOI "
      "(or by author-year where a study has none), because one source often yields many claims. "
      "Nothing here is a verdict: tiers are reported as ranges and counts, and the impact codes are "
      "never averaged. `q` and `i` are defined in the [Schema & Guide](CLAUDE.md) (evidence quality tiers and impact magnitude).")
    w("")
    w("## The corpus")
    w("")
    w(f"| | |\n|---|---|\n| Claims | {n_claims:,} |\n| Evidence entries | {entries:,} |\n"
      f"| Distinct studies | {len(studies):,} |\n"
      f"| Claims resting on one study | {spc[1]:,} ({_pct(spc[1], n_claims)}) |\n"
      f"| Claims with no coded evidence | {spc[0]:,} |\n"
      f"| Studies reporting an effect size | {with_effect:,} of {len(studies):,} ({_pct(with_effect, len(studies))}) |")
    w("")
    w("**Studies by quality tier** (where one study is coded differently on two claims, the tier most of its entries give):")
    w("")
    w("| q1 case / opinion / theory | q2 quasi-experiment, observational, narrative review | "
      "q3 experiment or systematic review | q4 pre-registered RCT or well-powered meta-analysis |")
    w("|---|---|---|---|")
    w("| " + " | ".join(f"{qs.get(q, 0):,} ({_pct(qs.get(q, 0), len(studies))})" for q in (1, 2, 3, 4)) + " |")
    w("")
    w("**Studies per claim:** " + ", ".join(
        f"{'4 or more' if k == 4 else k}: {spc.get(k, 0):,}" for k in (0, 1, 2, 3, 4)) + ".")
    w("")
    w("Most claims rest on one study because of how the wiki grows: an extraction turns one article into "
      "claims, so every new claim starts with exactly one source, and gains a second only when a later "
      "article is merged into it. The single-study share measures how much merging remains, as much as "
      "it measures the literature.")
    w("")

    w("## Load-bearing studies")
    w("")
    w("The studies the most claims rest on. A study that many claims *rest on alone* is a single point of "
      "failure: a correction to it, or a misreading of it, reaches every one of them.")
    w("")
    w("| Study | q | Claims citing it | Resting on it alone |")
    w("|---|---|---|---|")
    for key, cs in sorted(claims_of.items(), key=lambda kv: (-len(kv[1]), kv[0]))[:20]:
        title = studies.entries[key][0].get("title") or key
        example = sorted(cs)[0]
        q = studies.q(key)
        w(f"| [{_cell(_short(title))}](claims/{example}.md) | {('q' + str(q)) if q else '–'} | {len(cs)} | {alone.get(key, 0)} |")
    w("")

    w("## Citation load against evidence base")
    w("")
    w("The claims the rest of the wiki cites most, beside what they rest on. A claim cited from hundreds "
      "of pages on the strength of two studies is where one more study, or a replication, would matter most.")
    w("")
    w("| Claim | Cited from | Studies | q | Effect size reported |")
    w("|---|---|---|---|---|")
    ranked = sorted(claims, key=lambda c: (-len(citing.get(c, [])), c))
    for slug in ranked[:25]:
        st = er.Studies(claims, [slug])
        qv = st.q_values()
        qr = "–" if not qv else (f"q{min(qv)}" if min(qv) == max(qv) else f"q{min(qv)}–q{max(qv)}")
        eff = sum(1 for k in st.entries if st.reports_effect(k))
        w(f"| [{_cell(_short(claims[slug]['title'], 90))}](claims/{slug}.md) | {len(citing.get(slug, [])):,} pages "
          f"| {len(st)} | {qr} | {eff} of {len(st)} |")
    heavy = [c for c in claims if len(citing.get(c, [])) >= 50]
    thin = [c for c in heavy if per_claim[c] <= 1]
    w("")
    w(f"Of the {len(heavy)} claims cited from 50 or more pages, **{len(thin)} rest on one study or none**"
      + (": " + ", ".join(f"[{_cell(_short(claims[c]['title'], 70))}](claims/{c}.md)" for c in sorted(thin)) if thin else "")
      + ".")
    w("")

    w("## Contested claims")
    w("")
    w("Claims cited as support on some pages and as counter-evidence on others (`[+]` and `[-]` markers "
      "on the same claim). The disagreement is in how pages use the claim, which is often the point: a "
      "boundary condition cited against a strategy it limits. It is still where a reader should look twice.")
    w("")
    contested = [(c, Counter(p for p in citing[c] if p)) for c in citing]
    contested = [(c, p) for c, p in contested if p["+"] and p["-"]]
    w(f"{len(contested)} claims are cited both ways.")
    w("")
    w("| Claim | For | Mixed | Against | Studies |")
    w("|---|---|---|---|---|")
    for c, p in sorted(contested, key=lambda cp: (-cp[1]["-"], cp[0]))[:20]:
        w(f"| [{_cell(_short(claims[c]['title'], 90))}](claims/{c}.md) | {p['+']} | {p['~']} | {p['-']} | {per_claim.get(c, 0)} |")
    w("")

    w("## Evidence by kind of page")
    w("")
    w("Each page that cites claims carries its own profile under its title. Summarised by kind:")
    w("")
    w("| Kind | Pages | Citing a claim | Median studies behind a citing page | Citing pages whose claims have no studies |")
    w("|---|---|---|---|---|")
    for kind in er.PROFILE_KINDS:
        pages = [p.stem for p in sorted((WIKI_ROOT / kind).glob("*.md")) if p.stem != "index"]
        profs = [er.page_profile(cites.get((kind, s), []), claims) for s in pages]
        citing_p = [p for p in profs if p["claims"]]
        med = statistics.median([p["studies"] for p in citing_p]) if citing_p else 0
        none = sum(1 for p in citing_p if not p["studies"])
        w(f"| [{kind}]({kind}/index.md) | {len(pages):,} | {len(citing_p):,} | {med:g} | {none:,} |")
    w("")

    w("## Toward pooled estimates")
    w("")
    by_type = defaultdict(set)
    for f in sorted((WIKI_ROOT / "observations").glob("*.yaml")):
        if f.stem.startswith("example-"):
            continue      # synthetic fixtures declare themselves; they are not studies
        try:
            d = yaml.safe_load(f.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError:
            continue
        for o in d.get("observations") or []:
            mt = (o.get("result") or {}).get("measure_type")
            if mt:
                by_type[mt].add(f.stem)
    recs = set().union(*by_type.values()) if by_type else set()
    smd = set().union(*(by_type[t] for t in SMD_TYPES if t in by_type)) if by_type else set()
    conv = set().union(*(by_type[t] for t in CONVERTIBLE if t in by_type)) if by_type else set()
    w(f"A pooled effect size needs effect sizes with their uncertainty, on one scale, for comparable "
      f"contrasts and outcomes. Those are recorded in `observations/`, which holds **{len(recs)} study "
      f"records**: {len(smd)} report a standardised mean difference directly and {len(conv - smd)} more report "
      f"a statistic convertible to one (a correlation, an odds ratio, a partial η²). Fewer than three "
      f"studies are on that scale at all, so **no pooled estimate is reported**. The wiki's `i` codes are not "
      f"a substitute: they are bins, and averaging them would state a precision nobody measured."
      if len(smd) < 3 else
      f"A standardised-mean-difference family can now form; pooling it is a separate analysis step "
      f"that this page does not run.")
    w("")
    return "\n".join(L) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = build()
    if args.check:
        have = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if have != text:
            print(f"{OUT.name} is stale — run python3 scripts/build_evidence_report.py", file=sys.stderr)
            sys.exit(1)
        print(f"{OUT.name} is current")
        return
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.name}")


if __name__ == "__main__":
    main()
