#!/usr/bin/env python3
"""
build_reverse_index.py — who points at this page, as shippable data.

The design-spec pipeline's query is "given this element, which strategies apply
to these personas and this goal". The wiki answers it, but only backwards.

Measured (learning-design-spec findings/0008, reproduced by this script):

    edge                  forward            reverse
    principle -> strategy  43 / 198  (22%)   1747 / 2556  (68%)
    element   -> strategy      —             2376 / 2556  (93%)
    claim     -> strategy      —             2312 / 2556  (90%)

Three times the coverage, and the more trustworthy direction: the author of a
strategy knew which principle they were applying, while the author of a
principle page is guessing at which strategies might exemplify it. So this
does one pass over the corpus instead of anyone hand-populating `## Examples`
on 198 principle pages.

The output is committed, on purpose. CI on the design-spec side has no wiki
checkout, so an index that only exists after someone runs a script is an index
that side cannot use. It is regenerated by build_indexes.py, which the scrape
batch already runs, and `--check` fails when the committed copy is stale.

    python3 scripts/build_reverse_index.py            # write reverse-index.json
    python3 scripts/build_reverse_index.py --check    # is the committed copy current?
"""

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

WIKI_ROOT = Path(__file__).parent.parent
OUT_PATH = WIKI_ROOT / "reverse-index.json"

# Kinds that can be pointed AT — the ones carrying a stable id (see
# scripts/page_identity.py). Theories are included as targets because pages do
# link to them and the edge is free to collect, even though the spec does not
# read it yet.
TARGET_KINDS = ("elements", "principles", "patterns", "claims", "learner-variables", "theories")
# Kinds that can point. A strategy is the interesting source — it is the layer
# that says what to actually do — but a pattern citing a claim is an edge too.
SOURCE_KINDS = ("strategies", "patterns", "elements", "principles", "theories", "claims",
                "learner-variables")

SINGULAR = {"elements": "element", "principles": "principle", "patterns": "pattern",
            "claims": "claim", "learner-variables": "learner-variable", "theories": "theory",
            "strategies": "strategy"}

# ](../kind/slug.md) and ](kind/slug.md) and ](slug.md) — the wiki's three link
# spellings (see CLAUDE.md's cross-link conventions). The same-folder form has
# no kind in it, so the linking page's own folder supplies it.
LINK_RE = re.compile(r"\]\(<?(?:\.\./)?(?:/)?([a-z-]+/)?([^)>#]+?)\.md(?:#[^)>]*)?>?\)")

# The inline evidence marker that must follow a claim link (findings/0008,
# requirement 3). Captured here rather than in a second pass so the index can
# carry polarity and strength on the edge itself, which is what makes an
# evidence-weighted check possible on the design side.
MARKER_RE = re.compile(r"\A\s*\[([+~-])([SMW])\]")


def pages_of(kind: str):
    folder = WIKI_ROOT / kind
    if not folder.exists():
        return []
    return [p for p in sorted(folder.glob("*.md")) if p.stem != "index"]


def build() -> dict:
    known = {kind: {p.stem for p in pages_of(kind)} for kind in TARGET_KINDS}
    # target kind -> target slug -> source kind -> [ {slug, marker?} ]
    edges = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))
    forward_seen = defaultdict(set)

    for src_kind in SOURCE_KINDS:
        for path in pages_of(src_kind):
            text = path.read_text(encoding="utf-8")
            for m in LINK_RE.finditer(text):
                folder = (m.group(1) or "").rstrip("/") or src_kind
                slug = m.group(2).split("/")[-1]
                if folder not in known or slug not in known[folder]:
                    continue          # not a link to an identified page
                if folder == src_kind and slug == path.stem:
                    continue          # a page linking to itself
                entry = {"slug": path.stem}
                mk = MARKER_RE.match(text[m.end():])
                if mk:
                    entry["polarity"], entry["strength"] = mk.group(1), mk.group(2)
                bucket = edges[folder][slug][src_kind]
                if not any(e["slug"] == entry["slug"] for e in bucket):
                    bucket.append(entry)
                forward_seen[(src_kind, folder)].add(path.stem)

    out = {
        "note": ("Reverse edges: for each page, which pages link TO it. Built by "
                 "scripts/build_reverse_index.py; see its docstring for why this "
                 "direction rather than ## Examples."),
        "kinds": {k: SINGULAR[k] for k in TARGET_KINDS},
        "coverage": {f"{s}->{t}": len(v) for (s, t), v in sorted(forward_seen.items())},
        "totals": {k: len(pages_of(k)) for k in SOURCE_KINDS},
        "edges": {k: {slug: dict(by_src) for slug, by_src in sorted(v.items())}
                  for k, v in sorted(edges.items())},
    }
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed reverse-index.json is not what a "
                         "rebuild would produce")
    args = ap.parse_args()

    data = build()
    rendered = json.dumps(data, indent=1, sort_keys=True) + "\n"

    if args.check:
        if not OUT_PATH.exists():
            print(f"{OUT_PATH.name} is missing — run scripts/build_reverse_index.py")
            sys.exit(1)
        if OUT_PATH.read_text(encoding="utf-8") != rendered:
            print(f"{OUT_PATH.name} is stale — run scripts/build_reverse_index.py")
            sys.exit(1)
        print(f"{OUT_PATH.name} is current.")
        return

    OUT_PATH.write_text(rendered, encoding="utf-8")
    n_edges = sum(len(by_src[s]) for v in data["edges"].values()
                  for by_src in v.values() for s in by_src)
    print(f"Wrote {OUT_PATH.name}: {n_edges} edge(s) over "
          f"{sum(len(v) for v in data['edges'].values())} target page(s).\n")
    for pair, n in data["coverage"].items():
        src = pair.split("->")[0]
        total = data["totals"].get(src, 0)
        pct = f"{100 * n / total:.0f}%" if total else "—"
        print(f"  {pair:32} {n:5} / {total:5} source page(s) link this way  ({pct})")


if __name__ == "__main__":
    main()
