#!/usr/bin/env python3
"""
spot_check_duplicate_judge.py — Compare find_near_duplicates.py's GLM
(OpenRouter) verdicts against Sonnet on a random sample of the same
candidate groups, before trusting a cheap-model duplicate scan across the
whole wiki.

GLM 5.3 Flash has done well as a cheap WRITER for enrich.py — but judging
"is this really a duplicate, and if so which page should stay canonical"
is a different task, and nothing has actually confirmed GLM is a reliable
JUDGE for it. Cheap-and-good-at-writing doesn't automatically transfer to
cheap-and-good-at-judging. This runs both models on the same sample of
groups and reports where they agree/disagree, so a human can decide
whether GLM's verdicts are trustworthy enough to run unattended on the
rest, or whether disagreements are common enough to warrant Sonnet (or a
human) for the real pass.

Requires both OPENROUTER_API_KEY and ANTHROPIC_API_KEY.

Usage:
    # cross-folder collisions (find_cross_folder_duplicates.py's candidates)
    python3 scripts/spot_check_duplicate_judge.py --cross-folder --sample 10

    # a --type title-scan pass (stage 1 candidates generated by GLM by default)
    python3 scripts/spot_check_duplicate_judge.py --type strategies --sample 10
"""

import argparse
import random
import sys
from pathlib import Path

import find_cross_folder_duplicates as fcfd
import find_near_duplicates as fnd

WIKI_ROOT = Path(__file__).parent.parent


def _verdicts_agree(glm: dict, sonnet: dict) -> bool:
    return glm.get("is_duplicate") == sonnet.get("is_duplicate")


def _canonical(verdict: dict):
    return verdict.get("canonical_folder", verdict.get("canonical_slug"))


def spot_check_cross_folder(sample_n: int, seed: int, glm_model: str, sonnet_model: str) -> list:
    collisions = fcfd.find_collisions()
    items = list(collisions.items())
    random.seed(seed)
    sample = random.sample(items, k=min(sample_n, len(items)))

    glm_key = fnd._get_client("openrouter")
    sonnet_client = fnd._get_client("anthropic")

    rows = []
    for i, (slug, folders) in enumerate(sample, 1):
        print(f"[{i}/{len(sample)}] {slug} ({', '.join(folders)})", file=sys.stderr)
        glm_verdict = fnd.stage2_confirm_cross_folder(slug, folders, glm_key, glm_model)
        sonnet_verdict = fnd.stage2_confirm_cross_folder(slug, folders, sonnet_client, sonnet_model)
        rows.append({"label": f"{slug} ({', '.join(folders)})", "glm": glm_verdict, "sonnet": sonnet_verdict})
    return rows


def spot_check_type(page_type: str, sample_n: int, seed: int, glm_model: str, sonnet_model: str,
                     stage1_provider: str) -> list:
    pages = fnd.load_pages(page_type)
    stage1_client = fnd._get_client(stage1_provider)
    stage1_model = glm_model if stage1_provider == "openrouter" else sonnet_model
    print(f"Running stage 1 ({stage1_provider}) to generate candidate groups...", file=sys.stderr)
    groups = fnd.stage1_find_candidate_groups(pages, stage1_client, stage1_model)
    print(f"Stage 1 flagged {len(groups)} candidate group(s).", file=sys.stderr)
    if not groups:
        return []

    random.seed(seed)
    sample = random.sample(groups, k=min(sample_n, len(groups)))
    by_slug = {p["slug"]: p for p in pages}

    glm_key = fnd._get_client("openrouter")
    sonnet_client = fnd._get_client("anthropic")

    rows = []
    for i, g in enumerate(sample, 1):
        print(f"[{i}/{len(sample)}] {', '.join(g['slugs'])}", file=sys.stderr)
        glm_verdict = fnd.stage2_confirm_and_recommend(g, by_slug, glm_key, glm_model)
        sonnet_verdict = fnd.stage2_confirm_and_recommend(g, by_slug, sonnet_client, sonnet_model)
        rows.append({"label": ", ".join(g["slugs"]), "glm": glm_verdict, "sonnet": sonnet_verdict})
    return rows


def format_report(rows: list) -> str:
    if not rows:
        return "No candidate groups to compare."

    agree = sum(1 for r in rows if _verdicts_agree(r["glm"], r["sonnet"]))
    lines = [
        "# Duplicate-judge spot check: GLM vs Sonnet",
        "",
        f"{len(rows)} group(s) compared.",
        f"Agreement on is_duplicate: {agree}/{len(rows)} ({100 * agree / len(rows):.0f}%)",
        "",
    ]
    for r in rows:
        glm, sonnet = r["glm"], r["sonnet"]
        same = _verdicts_agree(glm, sonnet)
        marker = "AGREE" if same else "DISAGREE"
        lines.append(f"## {r['label']} — {marker}")
        lines.append(f"- GLM:    is_duplicate={glm.get('is_duplicate')}  canonical={_canonical(glm)}")
        lines.append(f"  - reasoning: {glm.get('reasoning')}")
        lines.append(f"- Sonnet: is_duplicate={sonnet.get('is_duplicate')}  canonical={_canonical(sonnet)}")
        lines.append(f"  - reasoning: {sonnet.get('reasoning')}")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--type", choices=fnd.PAGE_TYPES, help="Spot-check a --type title-scan pass")
    parser.add_argument("--cross-folder", action="store_true", help="Spot-check the --cross-folder pass")
    parser.add_argument("--sample", type=int, default=10, help="How many groups to compare (default: 10)")
    parser.add_argument("--seed", type=int, default=42, help="Random sample seed, for reproducible spot checks")
    parser.add_argument("--glm-model", default=fnd.OPENROUTER_DEFAULT_MODEL)
    parser.add_argument("--sonnet-model", default=fnd.MODEL_MAP["sonnet"])
    parser.add_argument("--stage1-provider", default="openrouter", choices=["anthropic", "openrouter"],
                        help="--type mode only: which provider generates the stage-1 candidate groups "
                             "to sample from (default: openrouter, matching the real run this is spot-checking)")
    parser.add_argument("--out", default=None, help="Write the report to this path instead of stdout")
    args = parser.parse_args()

    if not args.cross_folder and not args.type:
        parser.error("either --type or --cross-folder is required")
    if args.cross_folder and args.type:
        parser.error("--type and --cross-folder are mutually exclusive")

    if args.cross_folder:
        rows = spot_check_cross_folder(args.sample, args.seed, args.glm_model, args.sonnet_model)
    else:
        rows = spot_check_type(args.type, args.sample, args.seed, args.glm_model, args.sonnet_model,
                                args.stage1_provider)

    report = format_report(rows)
    if args.out:
        Path(args.out).write_text(report, encoding="utf-8")
        print(f"Wrote report to {args.out}", file=sys.stderr)
    else:
        print(report)


if __name__ == "__main__":
    main()
